# This file was generated by GoReleaser. DO NOT EDIT.
class StnsPasswd < Formula
  desc "STNS Password Management Command"
  homepage "https://github.com/STNS/stns-passwd"
  url "https://github.com/STNS/stns-passwd/releases/download/0.4.0/stns-passwd_0.4.0_darwin_amd64.tar.gz"
  version "0.4.0"
  sha256 "b6b4e8e35628dd56bfa7978925ce0b13869172a48844ab8122196b8298109ec8"

  def install
    bin.install 'stns-passwd'
  end

  test do
    system "#{bin}/stns-passwd"
  end
end
