# This file was generated by GoReleaser. DO NOT EDIT.
class StnsPasswd < Formula
  desc "STNS Password Management Command"
  homepage "https://github.com/STNS/stns-passwd"
  url "https://github.com/STNS/stns-passwd/releases/download/0.3.1/stns-passwd_0.3.1_darwin_amd64.tar.gz"
  version "0.3.1"
  sha256 "356e5965c5d9ba309f5c435761f19dd4f846e924c98cb058bd05c3a46b5a48cf"

  def install
    bin.install 'stns-passwd'
  end

  test do
    system "#{bin}/stns-passwd"
  end
end
